services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    container_name: mu-bo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/museum.db:/app/museum.db

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: mu-bo-admin
    ports:
      - "8080:80"
    depends_on:
      - backend
